### ISSUE TITLE
Plugin not being worked on anymore? MULTIPLE errors with other modules

### ISSUE THREAD

**Issue by santzuu** [jackriccomini/spamfilter-plugin-runelite#15]
I was wondering if this module is still being worked on or if it has been abandoned and I should just uninstall it since there are so many errors/compability issues with other plugins which make using this plugin either unusable or then you are not going to use 2-4 other plugins (could be even more, I have not tested that really...)

If you have "Chat filters" plugin turned on it does not allow you to filter overhead messages even if you have that setting turned on in spam filter. Also for the settings "collapse game chat" and "collapse player chat" in chat filter it does not put the repeating number correctly after repeated chat messages, so chat filter and spam filter plugins basically do not work AT ALL together which is sad. 

If you have the plugin "wise oldman" PLUS the setting "tranparent chat window" TURNED OFF the options "mark spam" and "mark ham" do not show up even. If you have wiseoldman plugin on you need to turn the transparent chat window option in osrs settings ON or then you need to turn the wiseoldman plugin off. 

Also as other users have mentioned - there is no option to "un spam" or "un ham" messages which would be super great... If there would be some option to unhide or to see what messages are currently being hidden as spam and somehow edit that... The plugin is super great as an idea but seems to be quite much still unfinished for actual usage or being used together with other plugins.

**Comment by jackriccomini** [comment]
No, it's not abandoned. I haven't spent time doing any plugin development for a while. **I still play and I still use the plugin.**

I wrote the plugin for myself to use. It's good enough for my own usage, so now I spend less time on it. I published it to the plugin hub because that's a better option for me than sideloading the plugin, which would require me to compile (and susequently re-compile after each update) and run a dev build of RuneLite on all my devices. I am glad other people are getting use out of the plugin and I'm happy to accept bug reports and fixes from other people! But I can't reasonably commit to spending any amount of time fixing smaller bugs in other peoples' workflows (although I will try to address game-breaking bugs like crashes, even if the best fix I can find is to pull the plugin from the plugin-hub for a while until I have time to fix it properly). The timeframe for those kinds of minor issues will always be "when I get around to it". It comes after my social life and hobbies.

I moved to a new PC about a month ago and haven't set up my RuneLite dev environment yet, in part because I haven't needed to. If already I'm doing some work on the plugin I might look at the issue tracker and think "while I'm here, I'll see what else I can fix". I'm sure you can understand that while Leagues is on, I'm more interested in playing the game than writing code for it!

I hope that clarifies things. I think if this plugin has conflicts with other plugins you need right now then your best bet is to disable it and check again in a few months.
