### ISSUE TITLE
Log out on catching a hell-rat

### ISSUE THREAD

**Issue by ArdiVeftvohl** [jackriccomini/spamfilter-plugin-runelite#4]
When I use my cat or hellcat to hunt a rat in the basement of evil dave the game crashes when my cat successfully catches a hell-rat. I don't know if this is the same when it comes to behemoth rats, I've only tried it on the small ones. This stops happening as soon as I disable this plugin.

**Comment by jackriccomini** [comment]
Thanks for the report! Presumably this is because of the chat line your character says after successfully catching a rat. I wonder if this is unique to cats or if the same applies to other actions which cause a player chat e.g. drinking a cup of tea.

I'm unable to replicate this right now since I'm not currently a member. I'm not aware of any actions which cause a player chat in F2P but if you can find one that also causes this crash then I'd be happy to log on and investigate myself.

There's a chance I'd be able to fix it without replicating it myself by taking a look at the log. To do this:

1. Cause a crash
2. Go to RuneLite's logs folder. You can find it by opening the screenshots folder (open RuneLite, right-click the camera icon). Then navigate one folder up (go to the folder which contains the "screenshots" folder) and look for the "logs" folder
3. Find "client.log" inside the "logs" folder and drag & drop it to attach it to a comment here

**Comment by zanda268** [comment]
I'm having the same issue myself. I'll pass you a bond if it helps you fix it. My IGN is Zanda268 as well.

The error itself is:
`2022-06-13 17:48:13 [Client] ERROR client-patch - Client error: 80,20,80,43,3075,9887,-64,107,-1,17,51,89,-57,107,30,0,8,72,101,121,32,119,101,108,108,32,100,111,110,101,32,112,117,115,115,44,32,121,111,117,32,103,111,116,32,105,116,33,0,
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(Unknown Source)
	at java.base/java.lang.String.charAt(Unknown Source)
	at la.m(lb.java:605)
	at q.q(q.java:178)
	at client.hw(client.java:7248)
	at client.ct(client.java:3082)
	at client.ag(client.java:1054)
	at aj.h(aj.java:368)
	at aj.run(aj.java:347)
	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by zephyrwc3** [comment]
> Thanks for the report! Presumably this is because of the chat line your character says after successfully catching a rat. I wonder if this is unique to cats or if the same applies to other actions which cause a player chat e.g. drinking a cup of tea.

So far, I haven't been able to find any other actions that cause this (such as drinking tea), only successfully catching a rat. I'm not sure exactly which function is being called from your code that is calling charAt, but adding some checks for empty strings should help? 

This plugin is great and I appreciate you making it, but made rat catchers quest hellish to complete because of the logout on successful catch. Was difficult to trace the error back to this plugin.

**Comment by geheur** [comment]
This is caused by setting the overhead text to "" for automated text e.g. dragon battleaxe spec or in this case probably from the player saying "go on catch that rat" or whatever. You should use overhead cycle setter instead of changing the text.

**Comment by zawe** [comment]
@jackriccomini plugin got disabled due to this issue.
Could you please let me know if you plan on fixing this? If not, I would be happy to fix it if no one does it first.

Thank you

**Comment by jackriccomini** [comment]
@zephyrwc3 Sorry to hear that! Ratcatchers is hellish enough already without plugin interference...

@geheur Thanks for the explanation! I haven't looked at RL's API in a while so just to clarify - you're saying that using `Actor.setOverheadCycle(0)` is the recommended way to clear overhead text?

@zawe I cancelled my membership for a bit as I was busy with life. I plan to pick it up again pretty soon to try the new content and I'm sure that when I do, I'll update the plugin. If you have a fix already (or if you can't wait) then you're very welcome to put in a PR

**Comment by jackriccomini** [comment]
@zanda268 Thanks very much for your offer of a bond! It's kind of you but it won't be necessary

**Comment by geheur** [comment]
@jackriccomini yes. https://discord.com/channels/301497432909414422/419891709883973642/1016427623460651018 in runelite discord here's the discussion about this.

**Comment by jackriccomini** [comment]
I've pushed a change that fixes the crash. I'll put in a PR to the plugin hub repository soon to get the plugin re-enabled
